# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(choices=[(b'accept', b'accept'), (b'reject', b'reject')], max_length=15)),
                ('responsed_at', models.DateTimeField(null=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('toUser', models.ManyToManyField(related_name='toUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members', through='membership.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='sgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sgroup', to='membership.SocialGroup'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='socialgroup',
            field=models.ForeignKey(default=b'1', on_delete=django.db.models.deletion.CASCADE, related_name='socialgroup', to='membership.SocialGroup'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='membership.SocialGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set([('invite', 'socialgroup')]),
        ),
    ]
